(executable
 (name connect)
 (modules connect common)
 (libraries neodriver neodriver_eio eio_main))

(executable
 (name run_cypher)
 (modules run_cypher common)
 (libraries neodriver neodriver_eio eio_main))

(executable
 (name create)
 (modules create common)
 (libraries neodriver neodriver_eio eio_main))

(executable
 (name transaction)
 (modules transaction common)
 (libraries neodriver neodriver_eio eio_main))

(executable
 (name managed_transaction)
 (modules managed_transaction common)
 (libraries neodriver neodriver_eio eio_main))
